### ISSUE TITLE
Disable Debug Output

### ISSUE THREAD

**Issue by ncioj10** [Daniel-Liu-c0deb0t/triple_accel#1]
Hi,
I'm pretty new to Rust so I'm not sure if there is a general way, but is it possible to disable the debug output (e.g. "Debug: Levenshtein Jewel vector type Avx1x32x8 for target "avx2".")? I want to still debug other parts of the code, but the I don't need the debug output of this library each time I use it.

Best,
Nicolas

**Comment by Daniel-Liu-c0deb0t** [comment]
That is a good point. I originally left the debug output in there (when debug assertions are enabled) because it is very helpful for debugging the crate. I am working on an update right now to only enable debug output when a feature flag is enabled.

**Comment by ncioj10** [comment]
Ok thanks a lot, this would be awesome!

**Comment by Daniel-Liu-c0deb0t** [comment]
Alright, if you use the latest `triple_accel = "0.3.2"` version, then debug output should be disabled by default. You can still get it for debugging purposes by specifying `--features "debug"` after `cargo test` or `cargo build`.

**Comment by ncioj10** [comment]
Thank you!
