### ISSUE TITLE
ARM 64 support

### ISSUE THREAD

**Issue by jianshu93** [Daniel-Liu-c0deb0t/triple_accel#11]
Hello Daniel， 

On the arm 64 apple cpu，neon is not supported right？

Thanks，

Jianshu

**Comment by Daniel-Liu-c0deb0t** [comment]
The Apple M1/M2 CPUs support Neon. `triple_accel` does not support Neon right now. I'm currently working on Neon support with block aligner here: https://github.com/Daniel-Liu-c0deb0t/block-aligner/pull/17

**Comment by jianshu93** [comment]
thanks ！

Jianshu
